name: Build All

on:
  workflow_dispatch:
    inputs:
      build_number:
        description: 'Build Number'
        default: 'auto'
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  NODE_VERSION: 17
  DOTNET_VERSION: '7.0.x'
  DOTNET_VERSION_COMPAT: '6.0.x'  

jobs:
  prepare:
    runs-on: ubuntu-latest

    outputs:
      build_number: ${{ steps.vars.outputs.build_number }}
      environment: ${{ steps.vars.outputs.environment }}

    steps:
      - uses: actions/checkout@v2
      - name: Define build number and version strings
        id: vars
        run: |
          build_number="${{ github.event.inputs.build_number }}"
          if [[ "${build_number}" == "auto" ]]; then
            build_number=${{ github.run_number }}
          fi
          environment="development"
          if [ "${{ github.ref_name }}" == "release" ] ; then
            environment="release"
          fi
          echo "::set-output name=build_number::${build_number}"
          echo "::set-output name=environment::${environment}"

  tests-unit-web:
    name: Unit and web tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Headquarters unit tests
        run: dotnet test src/Tests/WB.Tests.Unit
      - name: Headquarters web tests
        run: dotnet test src/Tests/WB.Tests.Web
      - name: Designer unit tests
        run: dotnet test src/Tests/WB.Tests.Unit.Designer

  tests-integration:
    name: Integration tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      PG_USER: postgres
      PG_PASSWORD: P@$$w0rd

    services:
      postgres:
        image: postgres:13.1
        env:
          POSTGRES_USER: ${{ env.PG_USER }}
          POSTGRES_PASSWORD: ${{ env.PG_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
 
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Create db connection string
        run: echo "DB_CONN=Server=postgres;Port=${{ job.services.postgres.ports[5432] }};User Id=${{ env.PG_USER }};Password=${{ env.PG_PASSWORD }};" >> $GITHUB_ENV

      - name: Headquarters tests
        run: |
          echo "[ConnectionStrings]\nTestConnection=\"${{ env.DB_CONN }}Database=postgres;CommandTimeout=60;\"" >> appsettings.ini
          dotnet test src/Tests/WB.Tests.Integration
      - name: Designer tests
        run: |
          echo "[ConnectionSettings]\nTestConnectionStringFormat=\"${{ env.DB_CONN }}Database=testdb_{0};CommandTimeout=60;\"" > appsettings.ini
          dotnet test src/Tests/WB.Tests.Integration.Designer

  mobile:
    needs: [prepare, tests-unit-web, tests-integration]
    runs-on: windows-2022
    environment: ${{ needs.prepare.outputs.environment }}

    strategy:
      matrix:
        task: [AndroidInterviewer, AndroidInterviewerWithMaps, AndroidSupervisor]

    steps:
    - name: Support longpaths
      run: |
        git config --system core.longpaths true
        New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" `
          -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force

    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'microsoft'
        java-version: '11'

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Setup Old .NET Core SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION_COMPAT }}

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.3

    - name: Build
      env:
        APP_CENTER_INTERVIEWER_DEV: ${{ secrets.APPCENTER_INTERVIEWER_KEY }}
        APP_CENTER_INTERVIEWER_PROD: ${{ secrets.APPCENTER_INTERVIEWER_KEY }} # will come with the prod value in the release environment
        APP_CENTER_SUPERVISOR_DEV: ${{ secrets.APPCENTER_SUPERVISOR_KEY }}
        APP_CENTER_SUPERVISOR_PROD: ${{ secrets.APPCENTER_SUPERVISOR_KEY }} # will come with the prod value in the release environment
        
      run: .\.build.ps1 ${{ matrix.task }} `
        -BuildNumber ${{ needs.prepare.outputs.build_number }} `
        -signapk -KeystoreAlias wbcapipublish `
        -androidKeyStore "${{ secrets.INTERVIEWER_KEYSTORE }}" `
        -KeystorePassword "${{ secrets.INTERVIEWER_KEYSTORE_PASSWORD }}" `
        -GoogleMapKey "${{ secrets.GOOGLEMAPS_KEY }}" `
        -ArcGisKey "${{ secrets.ARCGIS_KEY }}"
        -ArcGisApiKey "${{ secrets.ARCGIS_API_KEY }}"
       
    - name: Publish
      uses: actions/upload-artifact@v2
      with:
        name: Mobile Apps
        path: ${{ github.workspace }}/artifacts

  docker:
    needs: [prepare, mobile]
    runs-on: ubuntu-latest
    environment: ${{ needs.prepare.outputs.environment }}
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        task: [DockerHq, DockerDesigner, DockerWebTester]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        if: ${{ needs.prepare.outputs.environment == 'release' }}
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Download mobile artifacts
        if: ${{ matrix.task == 'DockerHq' }}
        id: download
        uses: actions/download-artifact@v2
        with:
          name: Mobile Apps
          path: artifacts

      - name: Build and push
        shell: pwsh
        run: |
          ./.build.ps1 ${{ matrix.task }} `
            -BuildNumber ${{ needs.prepare.outputs.build_number }} `
            -dockerRegistry ${{ env.REGISTRY }}/${{ github.repository }} `
            -apkFolder "artifacts" `
            -nodeVersion "${{ env.NODE_VERSION }}"

  installer:
    needs: [prepare, mobile]
    runs-on: windows-2019
    environment: ${{ needs.prepare.outputs.environment }}

    steps:
      - name: Support longpaths
        run: |
          git config --system core.longpaths true
          New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" `
            -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Setup WIX
        run: |
          Invoke-WebRequest -Uri https://wixtoolset.org/downloads/v3.14.0.6526/wix314-binaries.zip -OutFile wix314-binaries.zip
          Expand-Archive -Path wix314-binaries.zip -DestinationPath installer/wix314-binaries

      - name: Download mobile artifacts
        id: download
        uses: actions/download-artifact@v2
        with:
          name: Mobile Apps
          path: installer/artifacts

      - name: Save Code Signing Certificate
        if: ${{ needs.prepare.outputs.environment == 'release' }}
        run: |
          New-Item -ItemType directory -Path certificate
          Set-Content -Path certificate\certificate.txt -Value '${{ secrets.CODESIGNING_CERTIFICATE }}'
          certutil -decode certificate\certificate.txt certificate\certificate.pfx

      - name: Cache Frontend node modules
        uses: actions/cache@v3
        with:
          path: src/UI/WB.UI.Frontend/node_modules
          key: frontend-cache-node-modules-${{ hashFiles('src/UI/WB.UI.Frontend/package-lock.json') }}

      - name: Build Headquarters
        run: ./.build.ps1 PackageHqOffline -BuildNumber ${{ needs.prepare.outputs.build_number }}

      - name: Extract HQ Package
        run: |
          New-Item "HQsources" -ItemType Directory
          Expand-Archive -Path artifacts/WB.UI.Headquarters.Offline.zip -DestinationPath "HQsources"

      - name: Build installer
        id: build-installer
        run: |
          ./installer/build/build-installation.ps1 -HQSourcePath "HQsources" -ClientPath ${{ steps.download.outputs.download-path }} 
          $FileName = Get-ChildItem ./installer/src/SurveySolutionsBootstrap/bin/Release/SurveySolutions*.exe `
            | Select-Object -ExpandProperty FullName
          Write-Host "::set-output name=filename::$FileName"

      - name: Sign the installer
        if: ${{ needs.prepare.outputs.environment == 'release' }}
        run: |
          & installer/wix314-binaries/insignia.exe `
            -ib ${{ steps.build-installer.outputs.filename }} `
            -o engine.exe
          & 'C:/Program Files (x86)/Windows Kits/10/bin/x86/signtool.exe' sign `
            /f certificate\certificate.pfx `
            /p '${{ secrets.CODESIGNING_CERTIFICATE_PASSPHRASE }}' `
            /tr http://timestamp.sectigo.com /td sha256 /fd sha256 `
            engine.exe
          & installer/wix314-binaries/insignia `
            -ab engine.exe ${{ steps.build-installer.outputs.filename }} `
            -o ${{ steps.build-installer.outputs.filename }}
          & 'C:/Program Files (x86)/Windows Kits/10/bin/x86/signtool.exe' sign `
            /f certificate\certificate.pfx `
            /p '${{ secrets.CODESIGNING_CERTIFICATE_PASSPHRASE }}' `
            /tr http://timestamp.sectigo.com /td sha256 /fd sha256 `
            ${{ steps.build-installer.outputs.filename }}

      - name: Create draft release
        if: ${{ needs.prepare.outputs.environment == 'release' }}
        run: |
          $Version = Get-Content -Path ./src/.version
          $Title = if ($Version.split(".").count -eq 2) { "Release $Version" } else { "Hotfix $Version" }
          & gh release create "v$Version" `
          --target release `
          --draft `
          --title "$Title" `
          --notes '""' `
          --repo ${{ github.repository }} `
          "${{ steps.build-installer.outputs.filename }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        uses: actions/upload-artifact@v2
        with:
          name: Windows Installer
          path: ${{ steps.build-installer.outputs.filename }}
