name: "Pull Request Labeler"
on: 
  - pull_request

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true

  rc_label:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Action
        uses: hmarr/debug-action@v1.0.0

      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ github.event.pull_request.base.ref == 'rc' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            rc
        
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ github.event.pull_request.base.ref == 'master' && github.event.pull_request.head.ref == 'rc' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            automerge
            
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ github.event.pull_request.base.ref == 'master' && github.event.pull_request.head.ref == 'release' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            automerge
